POST http://localhost:8000/auth/realms/steam/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=steamlite-web&username=admin&password=admin&grant_type=password


###
POST http://localhost:8080/authent/inscription/
Content-Type: application/json

{ "pseudo": "Yoh",
  "mdp": "kali4",
  "email": "John@Doe.com"
}

###
POST http://localhost:8080/authent/inscription/
Content-Type: application/json

{ "pseudo": "John",
  "mdp": "gamma2",
  "email": "John@ahaha.com"
}
###
POST http://localhost:8080/authent/resetpassword
Content-Type: application/json

{
  "pseudo": "yoh",
  "mdp": "kali4"
}
###
POST http://localhost:8080/authent/token/
Content-Type: application/json

{
  "pseudo": "yoh",
  "mdp": "kali4"
}
###

