GET http://localhost:8080/vente/
token: {{auth_token}}

###
POST http://localhost:8080/vente/
token: {{auth_token}}
Content-Type: application/json

{
  "idJeu" : "2",
  "idClient" : "2",
  "prixAchat": "10.0",
  "dateAchat": "19/04/2022"
}

###
GET http://localhost:8080/vente/jeu/2
token: {{auth_token}}

###
GET http://localhost:8080/vente/client/1
token: {{auth_token}}

###
DELETE http://localhost:8080/vente/jeu/0
token: {{auth_token}}

###