GET http://localhost:8080/vente/
token: {{auth_token}}

###
POST http://localhost:8080/vente/
token: {{auth_token}}
Content-Type: application/json

{
  "idJeu" : "8",
  "idClient" : "2",
  "prixAchat": "30.0",
  "dateAchat": "19/04/2022"
}

###
GET http://localhost:8080/vente/jeu/7
token: {{auth_token}}

###
GET http://localhost:8080/vente/client/2
token: {{auth_token}}

###
DELETE http://localhost:8080/vente/jeu/3
token: {{auth_token}}

###