USE service_catalogue;


DROP TABLE IF EXISTS CATALOGUE;

CREATE TABLE CATALOGUE(
    idJeu INT AUTO_INCREMENT NOT NULL,
    nomJeu VARCHAR(25),
    dataAjout VARCHAR(255),
    nomF VARCHAR(255),
    CONSTRAINT PK_UTILISATEUR PRIMARY KEY(idJeu),
    UNIQUE(nomJeu)
);

