###
POST http://localhost:8082/social/message
Content-Type: application/json

{
  "receveur": 5,
  "envoyeur" : 1,
  "dateChat" : "20/03/2022",
  "message" : "WSHHHH"
}

###
GET http://localhost:8082/social/message
Content-Type: application/json

###
GET http://localhost:8082/social/recevoir
Content-Type: application/json

###
DELETE http://localhost:8082/social/1

###
DELETE http://localhost:8082/social/message/1/1