###
POST http://localhost:8080/social/message
Content-Type: application/json
token: {{auth_token}}

{
  "receveur": 5,
  "envoyeur" : 1,
  "dateChat" : "20/03/2022",
  "message" : "WSHHHH"
}
####
GET http://localhost:8080/fournisseur/fournisseurs
token: {{auth_token}}

###
GET http://localhost:8080/social/message
Content-Type: application/json
token: {{auth_token}}

###
GET http://localhost:8080/social/recevoir
Content-Type: application/json
token: {{auth_token}}

###
DELETE http://localhost:8080/social/1
token: {{auth_token}}

###
DELETE http://localhost:8080/social/message/1/1
token: {{auth_token}}