GET http://localhost:8080/catalogue/jeu

###
POST http://localhost:8080/catalogue/jeu
Content-Type: application/json

{
  "nomJeu" : "League of Legends",
  "dateJeu" : "18/04/2021",
  "nomF": "Tripod Studio",
  "prixJeu" : 15.0
}

###
GET http://localhost:8080/catalogue/jeu
Content-Type: application/json

###
DELETE http://localhost:8080/catalogue/jeu/5

###
GET http://localhost:8080/catalogue/jeu/3

###
GET http://localhost:8080/catalogue/jeu/1

###
DELETE http://localhost:8080/catalogue/jeu/1

###
PUT http://localhost:8080/catalogue/jeu/5
Content-Type: application/json

{
  "nomJeu" : "League of legends",
  "dateJeu" : "18/04/2021",
  "nomF": "Riot Games",
  "prixJeu" : 15.0
}