USE service_client;


DROP TABLE IF EXISTS CLIENT;

CREATE TABLE CLIENT(
    idC INT AUTO_INCREMENT NOT NULL,
    pseudo VARCHAR(25),
    mdp VARCHAR(255),
    dateInscrit date,
    CONSTRAINT PK_UTILISATEUR PRIMARY KEY(idC),
    UNIQUE(pseudo)
);


