USE steamlite;


DROP TABLE IF EXISTS CLIENT;

CREATE TABLE CLIENT(
    idC INT AUTO_INCREMENT NOT NULL,
    nomC VARCHAR(25),
    mdp VARCHAR(255),
    CONSTRAINT PK_UTILISATEUR PRIMARY KEY(idC),
    UNIQUE(nomC)
);


